app:
  test-emails:
    - test@oopsly.com
    - user1@oopsly.com
    - user2@oopsly.com
    - integration@oopsly.com
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
management:
  health:
    mail:
      enabled: false